apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: db
  labels: 
    app: mssql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
      containers:
      - name: mssql
        image: mcr.microsoft.com/azure-sql-edge:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: password
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
        resources:
          limits:
            memory: 4Gi
            cpu: "1"
          requests:
            memory: 2Gi
            cpu: "0.2"
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-data-claim