kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-claim
  namespace: db
spec:
  selector:
    matchLabels:
      app: mssql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi